CC=g++

vector1: vector1.cpp
	$(CC) vector1.cpp -o vector1
deque1: deque1.cpp
	$(CC) deque1.cpp -o deque1
array1: array1.cpp
	$(CC) -std=c++0x array1.cpp -o array1
list1: list1.cpp
	$(CC) list1.cpp -o list1
list2: list2.cpp
	$(CC) list2.cpp -o list2
forwardlist1: forwardlist1.cpp
	$(CC) -std=c++0x forwardlist1.cpp -o forwardlist1
multiset1: multiset1.cpp
	$(CC) -std=c++0x multiset1.cpp -o multiset1
multimap1: multimap1.cpp
	$(CC) -std=c++0x multimap1.cpp -o multimap1
unordmultiset1: unordmultiset1.cpp
	$(CC) -std=c++0x unordmultiset1.cpp -o unordmultiset1
unordmultimap1: unordmultimap1.cpp
	$(CC) -std=c++0x unordmultimap1.cpp -o unordmultimap1

.phony: all clean

all: vector1 deque1 array1 list1 list2 forwardlist1 multiset1 multimap1 unordmultiset1 unordmultimap1 \
	

clean: 
	rm -rvf vector1 deque1 array1 list1 list2 forwardlist1 multiset1 multimap1 unordmultiset1 unordmultimap1 \
		
